version: '3.8'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    volumes:
      - ./nats-server.conf:/etc/nats/nats-server.conf
      - ./jetstream_data:/jetstream_data # Ensure this directory exists on your host machine
